# Generated by Django 5.2.7 on 2025-12-12 19:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_demo",
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        help_text="Indicates whether this row was created in demo mode.",
                    ),
                ),
                ("slug", models.SlugField(unique=True)),
                ("title", models.CharField(max_length=255, unique=True)),
            ],
            options={
                "verbose_name_plural": "categories",
            },
        ),
        migrations.CreateModel(
            name="MenuItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_demo",
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        help_text="Indicates whether this row was created in demo mode.",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="The name of the menu item.",
                        max_length=255,
                        unique=True,
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        db_index=True,
                        decimal_places=2,
                        help_text="The price of the item in USD.",
                        max_digits=6,
                    ),
                ),
                (
                    "featured",
                    models.BooleanField(
                        db_index=True,
                        help_text="Indicates whether the item is featured.",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        help_text="The category this item belongs to.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="items",
                        to="restaurant.category",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "menu items",
            },
        ),
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_demo",
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        help_text="Indicates whether this row was created in demo mode.",
                    ),
                ),
                ("status", models.BooleanField(db_index=True, default=False)),
                ("total", models.DecimalField(decimal_places=2, max_digits=6)),
                ("date", models.DateField(db_index=True)),
                (
                    "delivery_crew",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="delivery_crew",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-date", "-id"],
            },
        ),
        migrations.CreateModel(
            name="Cart",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_demo",
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        help_text="Indicates whether this row was created in demo mode.",
                    ),
                ),
                ("quantity", models.SmallIntegerField()),
                ("unit_price", models.DecimalField(decimal_places=2, max_digits=6)),
                ("price", models.DecimalField(decimal_places=2, max_digits=6)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "menuitem",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="restaurant.menuitem",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["user", "menuitem"],
                        name="restaurant__user_id_10d8f8_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("user", "menuitem"), name="unique_user_menuitem"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="OrderItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("item_title", models.CharField(max_length=255)),
                ("quantity", models.SmallIntegerField()),
                ("unit_price", models.DecimalField(decimal_places=2, max_digits=6)),
                ("price", models.DecimalField(decimal_places=2, max_digits=6)),
                (
                    "menuitem",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="restaurant.menuitem",
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="order_items",
                        to="restaurant.order",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("menuitem__isnull", False)),
                        fields=("order", "menuitem"),
                        name="uniq_order_menuitem_when_present",
                    )
                ],
            },
        ),
    ]
