# Generated by Django 5.2.6 on 2025-09-26 19:51

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("restaurant", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={"verbose_name_plural": "categories"},
        ),
        migrations.AlterModelOptions(
            name="menuitem",
            options={"verbose_name_plural": "menu items"},
        ),
        migrations.AddField(
            model_name="category",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                help_text="Timestamp set automatically when the row is first created.",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="category",
            name="is_demo",
            field=models.BooleanField(
                db_index=True,
                default=False,
                help_text="Indicates whether this row was created/edited in demo mode.",
            ),
        ),
        migrations.AddField(
            model_name="category",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True,
                help_text="Timestamp updated automatically whenever the row is saved.",
            ),
        ),
        migrations.AddField(
            model_name="menuitem",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                help_text="Timestamp set automatically when the row is first created.",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="menuitem",
            name="is_demo",
            field=models.BooleanField(
                db_index=True,
                default=False,
                help_text="Indicates whether this row was created/edited in demo mode.",
            ),
        ),
        migrations.AddField(
            model_name="menuitem",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True,
                help_text="Timestamp updated automatically whenever the row is saved.",
            ),
        ),
        migrations.AlterField(
            model_name="category",
            name="slug",
            field=models.SlugField(unique=True),
        ),
        migrations.AlterField(
            model_name="category",
            name="title",
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name="menuitem",
            name="category",
            field=models.ForeignKey(
                help_text="The category this item belongs to.",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="items",
                to="restaurant.category",
            ),
        ),
        migrations.AlterField(
            model_name="menuitem",
            name="featured",
            field=models.BooleanField(
                db_index=True, help_text="Indicates whether the item is featured."
            ),
        ),
        migrations.AlterField(
            model_name="menuitem",
            name="price",
            field=models.DecimalField(
                db_index=True,
                decimal_places=2,
                help_text="The price of the item in USD.",
                max_digits=6,
            ),
        ),
        migrations.AlterField(
            model_name="menuitem",
            name="title",
            field=models.CharField(
                help_text="The name of the menu item.", max_length=255, unique=True
            ),
        ),
    ]
