# Generated by Django 5.2.6 on 2025-09-27 17:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("restaurant", "0002_alter_category_options_alter_menuitem_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderitem",
            name="item_title",
            field=models.CharField(default="", max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="menuitem",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="restaurant.menuitem",
            ),
        ),
    ]
