# Generated by Django 5.2.6 on 2025-09-30 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("restaurant", "0003_orderitem_item_title_alter_orderitem_menuitem"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="category",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="category",
            name="updated_at",
        ),
        migrations.RemoveField(
            model_name="menuitem",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="menuitem",
            name="updated_at",
        ),
        migrations.AddField(
            model_name="cart",
            name="is_demo",
            field=models.BooleanField(
                db_index=True,
                default=False,
                help_text="Indicates whether this row was created in demo mode.",
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="is_demo",
            field=models.BooleanField(
                db_index=True,
                default=False,
                help_text="Indicates whether this row was created in demo mode.",
            ),
        ),
        migrations.AlterField(
            model_name="category",
            name="is_demo",
            field=models.BooleanField(
                db_index=True,
                default=False,
                help_text="Indicates whether this row was created in demo mode.",
            ),
        ),
        migrations.AlterField(
            model_name="menuitem",
            name="is_demo",
            field=models.BooleanField(
                db_index=True,
                default=False,
                help_text="Indicates whether this row was created in demo mode.",
            ),
        ),
    ]
