# Generated by Django 5.2.6 on 2025-09-30 15:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("restaurant", "0004_remove_category_created_at_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="order",
            options={"ordering": ["-date", "-id"]},
        ),
        migrations.RemoveConstraint(
            model_name="orderitem",
            name="unique_order_menuitem",
        ),
        migrations.AddIndex(
            model_name="cart",
            index=models.Index(
                fields=["user", "menuitem"], name="restaurant__user_id_10d8f8_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="orderitem",
            constraint=models.UniqueConstraint(
                condition=models.Q(("menuitem__isnull", False)),
                fields=("order", "menuitem"),
                name="uniq_order_menuitem_when_present",
            ),
        ),
    ]
