# Generated by Django 5.2.6 on 2025-10-09 00:28

import apps.users.models.user
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={},
        ),
        migrations.AlterModelManagers(
            name="user",
            managers=[
                ("objects", apps.users.models.user.CustomUserManager()),
            ],
        ),
        migrations.AddField(
            model_name="user",
            name="uuid",
            field=models.UUIDField(
                blank=True, db_index=True, default=uuid.uuid4, editable=False, null=True
            ),
        ),
    ]
