# Generated by Django 5.2.6 on 2025-10-09 00:29

from django.db import migrations
import uuid


def backfill_user_uuid(apps, schema_editor):
    User = apps.get_model("users", "User")
    # Only rows where uuid is NULL
    for user in User.objects.filter(uuid__isnull=True).iterator():
        user.uuid = uuid.uuid4()
        user.save(update_fields=["uuid"])


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_alter_user_options_alter_user_managers_user_uuid"),
    ]

    operations = [
        migrations.RunPython(backfill_user_uuid, migrations.RunPython.noop),
    ]
